/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai_movie_recomender;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author root
 */
public class find_IT extends javax.swing.JFrame {

    /**
     * Creates new form find_IT
     */
    public find_IT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbgenero = new javax.swing.JTextField();
        tbcolor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_like = new javax.swing.JButton();
        btn_dislike = new javax.swing.JButton();
        btn_sugerir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lb_movie_title = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_imdb_link = new javax.swing.JLabel();
        lb_lis_pos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fint_IT");

        tbgenero.setName("tbgenero"); // NOI18N

        tbcolor.setName("tbcolor"); // NOI18N

        jLabel1.setText("genero:");

        jLabel2.setText("color:");

        jButton1.setText("cargar preferencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_like.setText("me gusta");
        btn_like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_likeActionPerformed(evt);
            }
        });

        btn_dislike.setText("no me gusta");
        btn_dislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dislikeActionPerformed(evt);
            }
        });

        btn_sugerir.setText("empezar a sugerir");
        btn_sugerir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sugerirActionPerformed(evt);
            }
        });

        jLabel3.setText("movie title");

        lb_movie_title.setText("         ");

        jLabel5.setText("movie link");

        lb_imdb_link.setText("           ");

        lb_lis_pos.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lb_movie_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_like, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(btn_dislike))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tbcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(tbgenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sugerir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_imdb_link))
                    .addComponent(lb_lis_pos))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_sugerir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_movie_title))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_imdb_link)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(lb_lis_pos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_like)
                    .addComponent(btn_dislike))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //declaracion de variables de uso general mapa de KNN y Pelicula dummie
    KNN_map mapa = new KNN_map(3,15);
    Pelicula dummie = new Pelicula("","",0.0,0.0,0.0,0.0,"",0.0,0.0,"","","",0.0,0.0,"",0.0,"","",0.0,"","","",0.0,0.0,0.0,0.0,0.0,0.0);
    List<Pelicula> peliculas = new ArrayList();
    double[] maximos = new double[8];
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            //obtencion de valores de filtrado inicial 
            String genero = this.tbgenero.getText();
            String color = this.tbcolor.getText();
            //lectura de archivo
            String archivo="C:\\Users\\LuisEmilio\\Documents\\gitrepo\\movie_recomender_hybrid_ai\\movie_metadata_unknown_add.csv";
            BufferedReader reader = new BufferedReader(new FileReader(archivo));
            String linea = reader.readLine();
            linea = reader.readLine();
            while(linea!=null)
            {
                Pelicula nueva_pelicula = dummie.pelicula_de_archivo(linea);
                if (nueva_pelicula.have_genre(genero)&&nueva_pelicula.color.equals(color))
                {
                  peliculas.add(nueva_pelicula);
                }
                linea=reader.readLine();
            }
            //parametros iniciales para funcion de precalculo
            maximos[0]=peliculas.get(0).director_facebook_likes;
            maximos[1]=peliculas.get(0).actor_3_facebook_likes;
            maximos[2]=peliculas.get(0).actor_1_facebook_likes;
            maximos[3]=peliculas.get(0).gross;
            maximos[4]=peliculas.get(0).cast_total_facebook_likes;
            maximos[5]=peliculas.get(0).imdb_score;
            maximos[6]=peliculas.get(0).aspect_ratio;
            maximos[7]=peliculas.get(0).movie_facebook_likes;
            //precalculo inicial 
            for (int i = 0; i < peliculas.size(); i++)
            {
             peliculas.get(i).calificar(maximos);
            }
            //asignacion de valores iniciales en el mapa 
            peliculas.sort((o1,o2)->Double.compare(o1.calificacion_inicial, o2.calificacion_inicial));
            mapa.train_point(peliculas.get(0).punto(), false);
            mapa.train_point(peliculas.get(1).punto(), false);
            mapa.train_point(peliculas.get(2).punto(), false);
            mapa.train_point(peliculas.get(peliculas.size()-1).punto(), true);
            mapa.train_point(peliculas.get(peliculas.size()-2).punto(), true);
            mapa.train_point(peliculas.get(peliculas.size()-3).punto(), true);
           
            
        }
        catch(Exception ex)
        {
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    Pelicula sugerencia;
    private void btn_sugerirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sugerirActionPerformed
        //Se va a calcular y sugerir la primera pelicula 
        for (int i = 0; i < peliculas.size(); i++)
        {
            if (mapa.prediccion(peliculas.get(i).punto()))
            {
                sugerencia = peliculas.get(i);
                peliculas.remove(i);
                break;
            }
        }
        lb_movie_title.setText(sugerencia.movie_title);
        lb_imdb_link.setText(sugerencia.movie_imdb_link);
    }//GEN-LAST:event_btn_sugerirActionPerformed

    private void btn_likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_likeActionPerformed
        // que hacer si una pelicula me parece buena
        if (sugerencia !=null) 
        {
           mapa.train_point(sugerencia.punto(),true);
        }
        else
        {
        
        }
    }//GEN-LAST:event_btn_likeActionPerformed

    private void btn_dislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dislikeActionPerformed
        // que hacer si una pelicula me parece mala
        if (sugerencia !=null) 
        {
           mapa.train_point(sugerencia.punto(),false);
        }
        else
        {
        
        }
    }//GEN-LAST:event_btn_dislikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(find_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(find_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(find_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(find_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new find_IT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dislike;
    private javax.swing.JButton btn_like;
    private javax.swing.JButton btn_sugerir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb_imdb_link;
    private javax.swing.JLabel lb_lis_pos;
    private javax.swing.JLabel lb_movie_title;
    private javax.swing.JTextField tbcolor;
    private javax.swing.JTextField tbgenero;
    // End of variables declaration//GEN-END:variables
}
